server:
  port: 8090
spring:
  application:
    name: nsnp-friend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itaobaob_user?serverTimezone=UTC
    username: root
    password: 123456.sql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-adress: ture