server:
  port: 9002
spring:
  application:
    name: nsnp-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.5.26.33:3306/itaobaob_base?serverTimezone=UTC
    username: root
    password: 123456.sql
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
  rabbitmq:
    host: 121.5.26.33
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-adress: ture